spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    sql:
      init:
        mode: always
        encoding: UTF-8
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}
jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 1800000
  refresh-token-validity: 604800000
  vector:
    collection-id: ${COLLECTION_ID}
fastapi:
  baseUrl: ${FAST_API_BASE_URL}
domain:
  baseUrl: ${DOMAIN_BASE_URL}