name: uplait-db

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: urecauser
      POSTGRES_PASSWORD: urecapassword
      POSTGRES_DB: uplait-database
    ports:
      - "6790:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: